run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - revive
    - gosec

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  stylecheck:
    checks: ["all", "-ST1005"]
  gosec:
    excludes:
      - G104 # unchecked error in defer or close
      - G304 # file path from variable (CLI argument)
      - G307 # defer Close error

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
