name: CI

on:
  workflow_call:

env:
  GOLANGCI_LINT_VERSION: v2.13

jobs:
  lint-and-test:
    name: Lint & test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Lint code
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Run tests with coverage
        run: go test -race -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: coverage.out
          fail_ci_if_error: true
          disable_telem: true
